version: "3"

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  build:
    internal: true
    cmds:
      - npm run build
    sources:
      - src/**/*.ts

  bench:
    desc: "Run benchmarks: task bench -- [lua5.1 | luajit | luajit-nojit] [file_pattern ...]"
    deps: [build]
    cmds:
      - npx tstl -p tsconfig.benchmark.json
      - npx tstl -p tsconfig.benchmark-jit.json
      - node scripts/bench.mjs {{.CLI_ARGS}}
